services:
  vault1:
    hostname: vault1.example.com
    build: .
    ports:
      - 8201:8200
    networks:
      vault:
        ipv4_address: 10.255.99.11
    environment:
      DOMAIN: "example.com"
      VAULT_ADDR: "https://vault1.example.com:8200"
      VAULT_CACERT: "/etc/vault/tls/ca/self_ca.crt"
    volumes:
      - ./config1.hcl:/etc/vault/config.hcl

  vault2:
    hostname: vault2.example.com
    build: .
    ports:
      - 8202:8200
    networks:
      vault:
        ipv4_address: 10.255.99.12
    environment:
      DOMAIN: "example.com"
      VAULT_ADDR: "https://vault2.example.com:8200"
      VAULT_CACERT: "/etc/vault/tls/ca/self_ca.crt"
    volumes:
      - ./config2.hcl:/etc/vault/config.hcl

  vault3:
    hostname: vault3.example.com
    build: .
    ports:
      - 8203:8200
    networks:
      vault:
        ipv4_address: 10.255.99.13
    environment:
      DOMAIN: "example.com"
      VAULT_ADDR: "https://vault3.example.com:8200"
      VAULT_CACERT: "/etc/vault/tls/ca/self_ca.crt"
    volumes:
      - ./config3.hcl:/etc/vault/config.hcl

networks:
  vault:
    ipam:
      driver: default
      config:
        - subnet: 10.255.99.0/24
