# docker build -t unseal:test -f Dockerfile.unseal .
FROM ubuntu:24.04

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install -y curl vim \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/* \
    && rm -rf /var/lib/apt/lists/*
